name: 'Deploy Update'
description: 'Github Action to deploy an update to IoT devices using JFrog Connect'
inputs:
  project_key:
    description: 'The project key (required)'
    required: true
  groups:
    description: 'The device group names in JSON format (optional)'
    required: false
    default: '[]'
  filters:
    description: 'The filters in JSON format (optional)'
    required: false
    default: '[]'
  flow_uuid:
    description: 'The Flow UUID (required)'
    required: true
  app_name:
    description: 'The Application Name (optional)'
    required: false
    default: ''
  app_version:
    description: 'The Application Version (optional)'
    required: false
    default: ''
  comment:
    description: 'The deployment comment (optional)'
    required: false
    default: 'Default comment'
  parameters_mapping:
    description: 'The mapping of parameters for the update configuration in JSON format (optional)'
    required: false
    default: '{}'
  token:
    description: 'The authorization token (required)'
    required: true
runs:
  using: 'node20'
  main: 'bin/run.js'
